#!/bin/sh
[ -d node_modules ] || npm ci
npm run build
tidy -modify -indent --indent-spaces 2 -quiet --tidy-mark no --wrap 0 --add-meta-charset yes index.html
site=narrowwidthshoes.kemitchell.com
scp ./*.html ./*.css "$site:/var/www/$site"
